# ---------- Base ----------
FROM node:20.20.2-alpine3.23 AS base

WORKDIR /app

FROM base AS build-deps
COPY package*.json ./
RUN npm ci

FROM build-deps AS build
COPY . .
RUN npm run build

# ---------- test ----------
FROM build-deps AS test
COPY . .
RUN npm run test

# ---------- prod ----------
FROM node:20.20.2-alpine3.23 AS prod
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=build /app/dist ./dist

USER node
EXPOSE 3000
CMD ["node", "dist/index.js"]