services:
  backend:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:3000
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - ORIGINS=${ORIGINS}
      - JWT_SECRET={$JWT_SECRET}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/app/
      - /app/node_modules
    command: sh -c "npm run tsx:dev"
    restart: unless-stopped

  db_pg:
    image: postgres:alpine
    restart: always
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
